import { useState } from "react";
import { Link } from "react-router-dom";
import StudentCard from "./StudentCard";
import ComparisonModal from "./ComparisonModal";
import "./Roommate.css";

// Full demo data with all CSV fields - 3 pairs
const DEMO_MATCHES = [
  // Pair 1: Joey Chestnut + Steve Irwin
  {
    student1: {
      studentId: '06482951',
      studentType: 'F',
      firstName: 'Joey',
      prefFirst: 'Joey',
      middleName: 'Michael',
      lastName: 'Chestnut',
      sex: 'Male',
      genderClarification: '',
      height: `5'10"`,
      birthDate: '03/15/2006',
      birthPlace: 'Newark, NJ',
      email: 'jchestnut@stanford.edu',
      phone: '(201) 555-0147',
      addressLine1: '142 Maple Street',
      addressLine2: 'Apt 3B',
      city: 'Jersey City',
      state: 'NJ',
      zip: '07302',
      countryCode: 'US',
      country: 'United States',
      lastSchool: 'Saint Peter\'s Preparatory School',
      attendedFamily: 'Uncle - Class of 1998',
      specialProgram: '',
      prefQuietRoom: '4',
      roomCleanliness: '5',
      roomStudy: '4',
      roomEnvironment: '4',
      musicImportance: '3',
      television: '2',
      weeknightSleep: '10pm-12am',
      weeknightWake: '6am-8am',
      weekendSleep: '12am-2am',
      weekendWake: '8am-10am',
      musicPrefer: 'Hip-hop, R&B, Lo-fi',
      musicFavorite: 'Kendrick Lamar, SZA, Frank Ocean',
      musicDontLike: 'Heavy metal',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'N',
      socialOutdoors: 'Y',
      socialRelax: 'Y',
      socialVolunteer: 'N',
      socialOther: 'N',
      socialOtherDetail: '',
      religiousPractices: 'N',
      socialArt: 'N',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: 'Club Ultimate Frisbee',
      roomOvernightGuest: 'Y',
      roomListenMusic: 'Y',
      roomMeditatePray: 'N',
      roomPractReligion: 'N',
      roomWatchTv: 'Y',
      roomSingInstrument: 'N',
      roomWithFriends: 'Y',
      roomVideoGames: 'Y',
      roomTimeAlone: 'Y',
      roomArtWork: 'N',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'N',
      isoAttendanceReason: '',
      isoStatus: '',
      identifyAs: 'Man',
      preferredRoomGender: 'Male-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I really value having a calm and focused space where I can get my work done during the week. I like to keep things pretty quiet on weeknights since I have early classes, but on weekends I definitely loosen up a bit. I love listening to music while I clean or just hang out, but I always keep the volume at a level where we can still have a conversation. I'm naturally an early riser—usually up around 6 or 7am—and I tend to wind down by 11pm most nights. I think having a roommate with a similar sleep schedule would make things way easier for both of us.`,
      concerns: `I'll be honest, I can be a little particular about keeping our shared space clean. It doesn't have to be spotless, but I get stressed when things pile up for too long. I also really need a dedicated desk area where I can focus on my coursework without distractions—studying on my bed just doesn't work for me. On weekends, I like having a couple friends over to hang out or watch movies, so I'd want a roommate who's cool with that. I always try to give a heads up beforehand though.`,
      name: 'Joey Chestnut',
      location: 'Jersey City, NJ',
    },
    student2: {
      studentId: '06571834',
      studentType: 'F',
      firstName: 'Steve',
      prefFirst: 'Steve',
      middleName: 'Robert',
      lastName: 'Irwin',
      sex: 'Male',
      genderClarification: '',
      height: `6'1"`,
      birthDate: '07/22/2006',
      birthPlace: 'Melbourne, Australia',
      email: 'sirwin@stanford.edu',
      phone: '+61 412 555 789',
      addressLine1: '28 Eucalyptus Lane',
      addressLine2: '',
      city: 'Melbourne',
      state: 'VIC',
      zip: '3000',
      countryCode: 'AU',
      country: 'Australia',
      lastSchool: 'Melbourne Grammar School',
      attendedFamily: '',
      specialProgram: '',
      prefQuietRoom: '4',
      roomCleanliness: '4',
      roomStudy: '5',
      roomEnvironment: '5',
      musicImportance: '3',
      television: '2',
      weeknightSleep: '10pm-12am',
      weeknightWake: '6am-8am',
      weekendSleep: '11pm-1am',
      weekendWake: '7am-9am',
      musicPrefer: 'Lo-fi, Indie, Acoustic',
      musicFavorite: 'Tame Impala, Bon Iver, Vance Joy',
      musicDontLike: 'Loud EDM',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'N',
      socialOutdoors: 'Y',
      socialRelax: 'Y',
      socialVolunteer: 'Y',
      socialOther: 'N',
      socialOtherDetail: '',
      religiousPractices: 'N',
      socialArt: 'Y',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: '',
      roomOvernightGuest: 'N',
      roomListenMusic: 'Y',
      roomMeditatePray: 'Y',
      roomPractReligion: 'N',
      roomWatchTv: 'Y',
      roomSingInstrument: 'N',
      roomWithFriends: 'Y',
      roomVideoGames: 'N',
      roomTimeAlone: 'Y',
      roomArtWork: 'Y',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'Y',
      isoAttendanceReason: '',
      isoStatus: 'Attending',
      identifyAs: 'Man',
      preferredRoomGender: 'Male-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I'm someone who thrives in a calm, organized environment. I do my best studying either in complete silence or with some chill lo-fi beats in the background—nothing too distracting. I've always been a morning person, so I'm usually up early and like to start my day with a routine. Having a consistent sleep schedule is really important to me because I tend to get cranky when I'm sleep-deprived. I'm not a party person by any means, but I do enjoy having meaningful conversations and just relaxing in the room after a long day.`,
      concerns: `One thing I should mention is that I'm pretty sensitive to strong scents—things like heavy cologne, candles, or air fresheners can give me headaches. I'd also appreciate if we could give each other a heads up before having guests over, just so neither of us is caught off guard. I have regular video calls with my family back home, usually in the evenings, so having some quiet time during those calls would mean a lot to me. Other than that, I'm pretty easygoing and just want us both to feel comfortable in our space.`,
      name: 'Steve Irwin',
      location: 'Melbourne, Australia',
    }
  },
  // Pair 2: Barack Obama + Mitt Romney
  {
    student1: {
      studentId: '06583921',
      studentType: 'F',
      firstName: 'Barack',
      prefFirst: 'Barack',
      middleName: 'Hussein',
      lastName: 'Obama',
      sex: 'Male',
      genderClarification: '',
      height: `6'1"`,
      birthDate: '08/04/2006',
      birthPlace: 'Honolulu, HI',
      email: 'bobama@stanford.edu',
      phone: '(808) 555-0144',
      addressLine1: '1234 Punahou Street',
      addressLine2: '',
      city: 'Honolulu',
      state: 'HI',
      zip: '96822',
      countryCode: 'US',
      country: 'United States',
      lastSchool: 'Punahou School',
      attendedFamily: '',
      specialProgram: 'Public Policy Scholars',
      prefQuietRoom: '4',
      roomCleanliness: '4',
      roomStudy: '5',
      roomEnvironment: '4',
      musicImportance: '4',
      television: '3',
      weeknightSleep: '11pm-1am',
      weeknightWake: '6am-8am',
      weekendSleep: '12am-2am',
      weekendWake: '8am-10am',
      musicPrefer: 'Jazz, Soul, Hip-hop',
      musicFavorite: 'Stevie Wonder, Miles Davis, Jay-Z',
      musicDontLike: 'Heavy metal',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'Y',
      socialOutdoors: 'Y',
      socialRelax: 'Y',
      socialVolunteer: 'Y',
      socialOther: 'Y',
      socialOtherDetail: 'Community organizing',
      religiousPractices: 'Y',
      socialArt: 'Y',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: 'Club Basketball',
      roomOvernightGuest: 'Y',
      roomListenMusic: 'Y',
      roomMeditatePray: 'Y',
      roomPractReligion: 'Y',
      roomWatchTv: 'Y',
      roomSingInstrument: 'N',
      roomWithFriends: 'Y',
      roomVideoGames: 'N',
      roomTimeAlone: 'Y',
      roomArtWork: 'N',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'Y',
      isoAttendanceReason: '',
      isoStatus: 'Attending',
      identifyAs: 'Man',
      preferredRoomGender: 'Male-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I thrive in an environment where I can balance focused study time with meaningful conversations. I love being around people who are passionate about making a difference, but I also need quiet moments to read and reflect. I'm a night owl when it comes to studying—some of my best thinking happens late at night—but I'm always up for an early morning basketball game. I appreciate a roommate who can engage in deep discussions about everything from policy to pop culture, but also respects when I need to zone out with some jazz playing softly in the background.`,
      concerns: `I tend to get really absorbed in whatever I'm working on, which means I might have papers and books spread out across my desk for days at a time. I promise there's a system to the chaos though! I also have a habit of staying up late reading or writing, so I'd need a roommate who's okay with a desk lamp being on past midnight sometimes. I'm pretty social and might have study groups or friends drop by, but I always try to be considerate about noise levels. Communication is key for me—I'd rather talk things out than let small issues build up.`,
      name: 'Barack Obama',
      location: 'Honolulu, HI',
    },
    student2: {
      studentId: '06594832',
      studentType: 'F',
      firstName: 'Mitt',
      prefFirst: 'Mitt',
      middleName: 'Willard',
      lastName: 'Romney',
      sex: 'Male',
      genderClarification: '',
      height: `6'2"`,
      birthDate: '03/12/2006',
      birthPlace: 'Detroit, MI',
      email: 'mromney@stanford.edu',
      phone: '(313) 555-0198',
      addressLine1: '456 Woodward Avenue',
      addressLine2: 'Suite 100',
      city: 'Detroit',
      state: 'MI',
      zip: '48226',
      countryCode: 'US',
      country: 'United States',
      lastSchool: 'Cranbrook Schools',
      attendedFamily: 'Father - Class of 1971',
      specialProgram: 'Business Leadership Program',
      prefQuietRoom: '5',
      roomCleanliness: '5',
      roomStudy: '5',
      roomEnvironment: '5',
      musicImportance: '2',
      television: '2',
      weeknightSleep: '10pm-11pm',
      weeknightWake: '5am-6am',
      weekendSleep: '10pm-11pm',
      weekendWake: '6am-7am',
      musicPrefer: 'Classical, Soft Rock',
      musicFavorite: 'The Beatles, Eagles, Mozart',
      musicDontLike: 'Rap, Heavy metal',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'N',
      socialOutdoors: 'Y',
      socialRelax: 'Y',
      socialVolunteer: 'Y',
      socialOther: 'Y',
      socialOtherDetail: 'Church activities',
      religiousPractices: 'Y',
      socialArt: 'N',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: '',
      roomOvernightGuest: 'N',
      roomListenMusic: 'Y',
      roomMeditatePray: 'Y',
      roomPractReligion: 'Y',
      roomWatchTv: 'Y',
      roomSingInstrument: 'N',
      roomWithFriends: 'Y',
      roomVideoGames: 'N',
      roomTimeAlone: 'Y',
      roomArtWork: 'N',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'Y',
      isoAttendanceReason: '',
      isoStatus: 'Attending',
      identifyAs: 'Man',
      preferredRoomGender: 'Male-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I'm someone who really values structure and discipline in my daily routine. I wake up early every day—usually around 5:30am—to exercise and get a head start on my responsibilities. I keep my space very organized because I find that a tidy environment helps me think more clearly. I don't drink caffeine or alcohol, so I tend to have pretty consistent energy levels throughout the day. I enjoy quiet evenings spent reading or having thoughtful conversations with friends. I'm looking for a roommate who shares my appreciation for an orderly, respectful living space.`,
      concerns: `I'll be upfront that I'm quite particular about cleanliness and organization. I make my bed every morning and prefer to keep common areas spotless. I'm also an early riser and early sleeper, so I'd need a roommate who can be mindful of noise levels in the late evening. My faith is very important to me, and I set aside time each day for prayer and scripture study, usually in the morning and evening. I don't expect my roommate to share my beliefs, but I'd appreciate mutual respect for each other's practices. I'm happy to discuss any concerns openly and work together to find solutions.`,
      name: 'Mitt Romney',
      location: 'Detroit, MI',
    }
  },
  // Pair 3: Taylor Swift + Sabrina Carpenter
  {
    student1: {
      studentId: '06605743',
      studentType: 'F',
      firstName: 'Taylor',
      prefFirst: 'Taylor',
      middleName: 'Alison',
      lastName: 'Swift',
      sex: 'Female',
      genderClarification: '',
      height: `5'11"`,
      birthDate: '12/13/2006',
      birthPlace: 'West Reading, PA',
      email: 'tswift@stanford.edu',
      phone: '(610) 555-0113',
      addressLine1: '78 Wyomissing Boulevard',
      addressLine2: '',
      city: 'West Reading',
      state: 'PA',
      zip: '19611',
      countryCode: 'US',
      country: 'United States',
      lastSchool: 'Aaron Academy (Homeschool)',
      attendedFamily: '',
      specialProgram: '',
      prefQuietRoom: '3',
      roomCleanliness: '4',
      roomStudy: '3',
      roomEnvironment: '3',
      musicImportance: '5',
      television: '3',
      weeknightSleep: '12am-2am',
      weeknightWake: '8am-10am',
      weekendSleep: '2am-4am',
      weekendWake: '10am-12pm',
      musicPrefer: 'Pop, Country, Indie Folk',
      musicFavorite: 'Joni Mitchell, Fleetwood Mac, Phoebe Bridgers',
      musicDontLike: 'Screamo',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'Y',
      socialOutdoors: 'N',
      socialRelax: 'Y',
      socialVolunteer: 'Y',
      socialOther: 'Y',
      socialOtherDetail: 'Songwriting',
      religiousPractices: 'N',
      socialArt: 'Y',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: '',
      roomOvernightGuest: 'Y',
      roomListenMusic: 'Y',
      roomMeditatePray: 'N',
      roomPractReligion: 'N',
      roomWatchTv: 'Y',
      roomSingInstrument: 'Y',
      roomWithFriends: 'Y',
      roomVideoGames: 'N',
      roomTimeAlone: 'Y',
      roomArtWork: 'Y',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'Y',
      isoAttendanceReason: '',
      isoStatus: 'Attending',
      identifyAs: 'Woman',
      preferredRoomGender: 'Female-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I'm a creative soul who needs space to write, play guitar, and let my ideas flow freely. My ideal room vibe is cozy and inspiring—think fairy lights, lots of candles, and maybe some vintage decor. I tend to be a night owl because that's when I feel most creative, so I do my best work after midnight. I love having deep conversations with friends, baking cookies at 2am, and spontaneous dance parties. I'm looking for a roommate who appreciates music, doesn't mind occasional guitar playing, and values genuine friendship over just being "roommates."`,
      concerns: `I should warn you that I sometimes get bursts of creative inspiration at odd hours, which might mean quietly strumming my guitar or scribbling lyrics at 3am. I always try to be considerate though—I use headphones when I can and keep the acoustic stuff soft. I'm also someone who processes emotions through journaling and music, so I might need space to be in my feelings sometimes. I have cats back home that I miss terribly, so I might FaceTime them (yes, my mom holds up the phone to them). I'm fiercely loyal to my friends and would do anything for a roommate who becomes part of my inner circle.`,
      name: 'Taylor Swift',
      location: 'West Reading, PA',
    },
    student2: {
      studentId: '06616654',
      studentType: 'F',
      firstName: 'Sabrina',
      prefFirst: 'Sabrina',
      middleName: 'Annlynn',
      lastName: 'Carpenter',
      sex: 'Female',
      genderClarification: '',
      height: `5'0"`,
      birthDate: '05/11/2006',
      birthPlace: 'Quakertown, PA',
      email: 'scarpenter@stanford.edu',
      phone: '(215) 555-0127',
      addressLine1: '321 Broad Street',
      addressLine2: '',
      city: 'Quakertown',
      state: 'PA',
      zip: '18951',
      countryCode: 'US',
      country: 'United States',
      lastSchool: 'Quakertown Community High School',
      attendedFamily: 'Sister - Class of 2027',
      specialProgram: '',
      prefQuietRoom: '3',
      roomCleanliness: '4',
      roomStudy: '3',
      roomEnvironment: '3',
      musicImportance: '5',
      television: '4',
      weeknightSleep: '1am-3am',
      weeknightWake: '9am-11am',
      weekendSleep: '2am-4am',
      weekendWake: '10am-12pm',
      musicPrefer: 'Pop, Broadway, R&B',
      musicFavorite: 'Ariana Grande, Beyoncé, Sondheim',
      musicDontLike: 'Country',
      socialCultural: 'Y',
      socialExercise: 'Y',
      socialParties: 'Y',
      socialOutdoors: 'N',
      socialRelax: 'Y',
      socialVolunteer: 'N',
      socialOther: 'Y',
      socialOtherDetail: 'Acting, Performing',
      religiousPractices: 'N',
      socialArt: 'Y',
      studentClubs: 'Y',
      reading: 'Y',
      partTimeWork: 'N',
      varsitySport: '',
      walkOnSport: '',
      roomOvernightGuest: 'Y',
      roomListenMusic: 'Y',
      roomMeditatePray: 'N',
      roomPractReligion: 'N',
      roomWatchTv: 'Y',
      roomSingInstrument: 'Y',
      roomWithFriends: 'Y',
      roomVideoGames: 'N',
      roomTimeAlone: 'Y',
      roomArtWork: 'Y',
      roomCallFamily: 'Y',
      foodAllergy: 'N',
      foodAllergyDetail: '',
      religiousNeed: '',
      smoking: 'N',
      isoAttendance: 'Y',
      isoAttendanceReason: '',
      isoStatus: 'Attending',
      identifyAs: 'Woman',
      preferredRoomGender: 'Female-identifying',
      preferredRoomGenderExplained: '',
      optimalVibe: `I'm basically a theater kid at heart, so I need a roommate who won't judge me for randomly breaking into song or practicing my lines out loud. I love creating a fun, vibrant space with lots of personality—think pink accents, fun posters, and good lighting for selfies (important!). I'm definitely more of a night person and tend to get energized as the day goes on. I'm super social and love having friends over for movie nights, doing each other's makeup, or just hanging out and talking for hours. I want our room to feel like a place where we can both be ourselves completely.`,
      concerns: `Okay so full disclosure: I can be kind of loud sometimes. Not in a rude way, but I'm just naturally expressive and my laugh carries. I also practice singing pretty regularly, and while I try to do it when my roommate is out, sometimes inspiration strikes! I'm a bit of a perfectionist about my appearance, so I might take over the bathroom mirror longer than expected—I promise to give fair warning though. I also have a lot of stuff (clothes, shoes, skincare... it's a problem) so I'd need a roommate who's okay with me being a little extra. But I'm also incredibly supportive and will be your biggest cheerleader!`,
      name: 'Sabrina Carpenter',
      location: 'Quakertown, PA',
    }
  }
];

function RoommateIndex() {
  const [currentPairIndex, setCurrentPairIndex] = useState(0);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isFinished, setIsFinished] = useState(false);

  const currentPair = DEMO_MATCHES[currentPairIndex];

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
  };

  const handleNextPair = () => {
    if (currentPairIndex < DEMO_MATCHES.length - 1) {
      setCurrentPairIndex(currentPairIndex + 1);
    } else {
      setIsFinished(true);
    }
  };

  if (isFinished) {
    return (
      <div className="roommate-page roommate-finished">
        <div className="finished-content">
          <h1>You finished approving matches!</h1>
          <Link to="/" className="back-link">
            ← Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="roommate-page">
      <Link to="/" className="back-link">
        ← Back to Dashboard
      </Link>

      <header className="roommate-header">
        <h1>These students have compatible living habits. Review the match below.</h1>
      </header>

      <div className="roommate-cards">
        <StudentCard student={currentPair.student1} onSeeMore={handleOpenModal} />
        <StudentCard student={currentPair.student2} onSeeMore={handleOpenModal} />
      </div>

      <div className="roommate-actions">
        <div className="action-btn-row">
          <button className="action-btn action-btn--reject" onClick={handleNextPair}>
            Reject
          </button>
          <button className="action-btn action-btn--approve" onClick={handleNextPair}>
            Approve
          </button>
        </div>
        <button className="skip-btn" onClick={handleNextPair}>Save for Later</button>
      </div>

      {isModalOpen && (
        <ComparisonModal
          student1={currentPair.student1}
          student2={currentPair.student2}
          onClose={handleCloseModal}
        />
      )}
    </div>
  );
}

export default RoommateIndex;
